// <auto-generated />
using System;
using Invoici.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Invoici.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Invoici.Models.Invoice", b =>
                {
                    b.Property<string>("InvoiceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GSTNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("InvoiceId");

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            InvoiceId = "1",
                            Date = new DateTime(2024, 11, 11, 11, 30, 13, 403, DateTimeKind.Local).AddTicks(3320),
                            Description = "Office Supplies Purchase",
                            GSTNumber = "27AABCU9603R1ZV",
                            PartyName = "ABC Corporation"
                        },
                        new
                        {
                            InvoiceId = "2",
                            Date = new DateTime(2024, 11, 11, 11, 30, 13, 403, DateTimeKind.Local).AddTicks(3323),
                            Description = "IT Services Billing",
                            GSTNumber = "27AAECS1223M1ZV",
                            PartyName = "XYZ Industries"
                        },
                        new
                        {
                            InvoiceId = "3",
                            Date = new DateTime(2024, 11, 11, 11, 30, 13, 403, DateTimeKind.Local).AddTicks(3325),
                            Description = "Raw Materials Invoice",
                            GSTNumber = "27AAGCS1223R1ZV",
                            PartyName = "LMN Traders"
                        });
                });

            modelBuilder.Entity("Invoici.Models.InvoiceItem", b =>
                {
                    b.Property<int>("InvoiceItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceItemId"));

                    b.Property<string>("HSNCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("InvoiceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Particular")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("InvoiceItemId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceItems");

                    b.HasData(
                        new
                        {
                            InvoiceItemId = 1,
                            HSNCode = "1234",
                            InvoiceId = "1",
                            Particular = "Product A",
                            Quantity = 5,
                            Rate = 100m
                        },
                        new
                        {
                            InvoiceItemId = 2,
                            HSNCode = "5678",
                            InvoiceId = "1",
                            Particular = "Product B",
                            Quantity = 3,
                            Rate = 200m
                        },
                        new
                        {
                            InvoiceItemId = 3,
                            HSNCode = "9012",
                            InvoiceId = "2",
                            Particular = "Service C",
                            Quantity = 1,
                            Rate = 500m
                        });
                });

            modelBuilder.Entity("Invoici.Models.InvoiceItem", b =>
                {
                    b.HasOne("Invoici.Models.Invoice", "Invoices")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("Invoici.Models.Invoice", b =>
                {
                    b.Navigation("InvoiceItems");
                });
#pragma warning restore 612, 618
        }
    }
}
